### ISSUE TITLE
check rendering of examples on website

### ISSUE THREAD

**Issue by mvdoc** [gallantlab/pymoten#24]
Example: [https://gallantlab.github.io/pymoten/auto_examples/introduction/demo_show_filters.html#sphx-glr-auto-examples-introduction-demo-show-filters-py](Visualizing the motion energy filters)

- the first image doesn't show anything
- there's an extra output at the end due to setting ticks

BTW this example is really cool

**Comment by anwarnunez** [comment]
yo',

the first image is an artifact. this is where the animation is played. the figure is then captured by sphinx gallery and embedded in the html. in order to remove it, we need to modify the first code block to include parts of the last code block, which adds unnecessary complexity to the example. (the first version of the example was like that).  

sphinx gallery recently added animation support. however, it did not work here. the current animation support in sphinx gallery might be restricted to a subset of matplotlib animations. or maybe i didn't follow their instructions correctly.

I'll leave this issue open so that we can look into it in the future.

**Comment by mvdoc** [comment]
fixed by #34  #36
